### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by cunningb** [SBPrime/AsyncWorldEdit-Premium#131]
AsyncWorldEdit v3.4.9
WorldEdit v6.1.3;7a097ca
PaperSpigot - 1.10.2-R0.1 (8e220b8)

An error occurs while doing a clipboard paste. Causes a job to never be finished.

```
[14:43:53] [Craft Scheduler Thread - 31/WARN]: org.apache.commons.lang.UnhandledException: Plugin AsyncWorldEdit v3.4.9 generated an exception while executing task 42346
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IncompatibleClassChangeError: Class org.bukkit.plugin.PluginDescriptionFile does not implement the requested interface com.sk89q.worldedit.bukkit.adapter.BukkitImplAdapter
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:405)
        at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$38.execute(AsyncWorld.java:1032)
        at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$38.execute(AsyncWorld.java:1029)
        at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:644)
        at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getBlock(AsyncWorld.java:1029)
        at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.setBlock(AsyncWorld.java:315)
        at org.primesoft.asyncworldedit.worldedit.world.CancelableWorld.setBlock(CancelableWorld.java:156)
        at com.sk89q.worldedit.extent.world.FastModeExtent.setBlock(FastModeExtent.java:92)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.world.SurvivalModeExtent.setBlock(SurvivalModeExtent.java:88)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.world.BlockQuirkExtent.setBlock(BlockQuirkExtent.java:64)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.world.ChunkLoadingExtent.setBlock(ChunkLoadingExtent.java:66)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:67)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:111)
        at org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:80)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:93)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:64)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69)
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
        at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:87)
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:503)
        at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:383)
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:546)
        at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:395)
        at com.sk89q.worldedit.CuboidClipboard.place(CuboidClipboard.java:439)
        at com.sk89q.worldedit.CuboidClipboard.paste(CuboidClipboard.java:407)
        at com.worldbuilder.WorldBuilder$2.execute(WorldBuilder.java:321)
        at com.worldbuilder.WorldBuilder$2.execute(WorldBuilder.java:318)
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$2.task(BlockPlacer.java:1204)
        at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:64)
        at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:142)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
```

**Comment by SBPrime** [comment]
Please provide:
1. Exact version of WorldEdit (or link to jar)
2. Exact version of spigot (or link to jar)
3. Full server startup log

**Comment by cunningb** [comment]
Those are the exact versions of WorldEdit and PaperSpigot, they just include the commit hash from the last commit they were built from.

That WorldEdit was built from this commit https://github.com/sk89q/WorldEdit/commit/7a097ca and can be downloaded here https://dev.bukkit.org/projects/worldedit/files/922048

PaperSpigot was a custom build from this commit https://github.com/PaperMC/Paper/commit/8e220b8
https://www.dropbox.com/s/qw2zakbxaq8s8f2/paper.jar?dl=0

I'm unable to provide a full server startup log at this time.

**Comment by SBPrime** [comment]
This was caused by compatibility issue. Injector changes in 3.6.0 should prevent this from happening in the future.
