### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by HiJackerRZ** [SBPrime/AsyncWorldEdit-Premium#140]
[18:46:43] [Server thread/WARN]: [AsyncWorldEdit] Task #8 for AsyncWorldEdit v3.4.10 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.TileEntity.a(Lnet/minecraft/server/v1_12_R1/NBTTagCompound;)V
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.readTagIntoTileEntity(Spigot_v1_12_R1.java:116) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1.setBlock(Spigot_v1_12_R1.java:253) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:416) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:305) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:296) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.entries.WorldFuncEntryEx.process(WorldFuncEntryEx.java:79) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:446) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:373) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:84) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:263) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-edd0396-63029f4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by SBPrime** [comment]
You need to update the WorldEdit.
