### ISSUE TITLE
Undo does not working

### ISSUE THREAD

**Issue by ghost** [SBPrime/AsyncWorldEdit-Premium#147]
| Name           | Version       |
|----------------|---------------|
| Java | 8 |
| Paper          | [#446 (1.13.2)](https://papermc.io/ci/job/Paper-1.13/446/) |
| WorldEdit      | [#3944-ee8602b](http://builds.enginehub.org/job/worldedit/10622) |
| AsyncWorldEdit | 3.6.0-beta-9  |

#### `//undo` after `//regen` (operations won't create undo file)
```
[10:17:21] [Server thread/INFO]: *** issued server command: //regen
[10:17:21] [Server thread/INFO]: WorldEdit: *** (in "world"): /regen - Region: (389, 68, 442) - (417, 70, 461)
[10:17:28] [Server thread/INFO]: *** issued server command: //undo
[10:17:28] [Server thread/INFO]: WorldEdit: *** (in "world"): /undo
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] ***********************************
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] Unable to create undo iterator for ts.16735c6374a.ad6d46d3.7
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] ***********************************
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * Exception: java.io.FileNotFoundException
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * Error message: plugins/AsyncWorldEdit/undo/6e71****-****-****-****-************/ts.16735c6374a.ad6d46d3.7 (No such file or directory)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * Stack: 
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.open0(Native Method)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.open(RandomAccessFile.java:316)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.changesetSerializer.iterators.BaseFileIterator.initializeStream(BaseFileIterator.java:121)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.changesetSerializer.iterators.UndoFileBackwordIterator.initializeStream(UndoFileBackwordIterator.java:88)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.initializeIterator(FileChangeSet.java:325)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.FileChangeSet.backwardIterator(FileChangeSet.java:134)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.ThreadSafeChangeSet.backwardIterator(ThreadSafeChangeSet.java:100)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.history.changeset.MemoryMonitorChangeSet.backwardIterator(MemoryMonitorChangeSet.java:171)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doUndo(ThreadSafeEditSession.java:806)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:78)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:155)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[10:17:28] [Craft Scheduler Thread - 77/INFO]: [AsyncWorldEdit] ***********************************
```

#### `//undo` after `//paste` (and block queue won't automatically clear)
```
[11:55:12] [Server thread/INFO]: **** issued server command: //paste
[11:55:12] [Server thread/INFO]: WorldEdit: **** (in "world"): /paste - Position: (476.0, 128.0, 608.0)
[11:55:29] [Server thread/INFO]: **** issued server command: //undo
[11:55:29] [Server thread/INFO]: WorldEdit: **** (in "world"): /undo
[11:55:29] [Craft Scheduler Thread - 216/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-beta-9 generated an exception while executing task 968
java.lang.AbstractMethodError: null
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
	at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:102) ~[?:?]
	at com.sk89q.worldedit.history.change.BlockChange.undo(BlockChange.java:88) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.UndoProcessor.resume(UndoProcessor.java:119) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.__34f2b4a76b384a6eaa9652626bd47ed8__completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__34f2b4a76b384a6eaa9652626bd47ed8__completeBlindly.execute(Unknown Source) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:76) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:83) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:155) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-448]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-448]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by SBPrime** [comment]
Are you using core protect?

**Comment by ghost** [comment]
@SBPrime Yes. I forgot to upload my plugins list
```
AsyncWorldEdit
AsyncWorldEdit-TitleManager
BlocksHub
CoreProtect
DiscordSRV
LuckPerms
LWC
NoPlugins
OpenInv
ProtocolLib
Spartan
TitleManager
WorldEdit
WorldGuard
```

**Comment by SBPrime** [comment]
Please send me the coreprotect config.

**Comment by ghost** [comment]
```yaml
#CoreProtect Config

# If enabled, extra data is displayed when doing rollbacks and restores.
# If disabled, you can manually trigger it in-game by adding "#verbose"
# to the end of your rollback statement.
verbose: true

# MySQL is optional and not required.
# If you prefer to use MySQL, enable the following and fill out the fields.
use-mysql: false
table-prefix: co_
mysql-host: 127.0.0.1
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: 

# If enabled, CoreProtect will check for updates when your server starts up.
# If an update is available, you'll be notified via your server console.
check-updates: true

# If enabled, other plugins will be able to utilize the CoreProtect API.
api-enabled: true

# If no radius is specified in a rollback or restore, this value will be
# used as the radius. Set to "0" to disable automatically adding a radius.
default-radius: 10

# The maximum radius that can be used in a command. Set to "0" to disable.
# To run a rollback or restore without a radius, you can use "r:#global".
max-radius: 100

# If enabled, items taken from containers (etc) will be included in rollbacks.
rollback-items: true

# If enabled, entities, such as killed animals, will be included in rollbacks.
rollback-entities: true

# If enabled, generic data, like zombies burning in daylight, won't be logged.
skip-generic-data: true

# Logs blocks placed by players.
block-place: true

# Logs blocks broken by players.
block-break: true

# Logs blocks that break off of other blocks; for example, a sign or torch
# falling off of a dirt block that a player breaks. This is required for
# beds/doors to properly rollback.
natural-break: true

# Properly track block movement, such as sand or gravel falling.
block-movement: true

# Properly track blocks moved by pistons.
pistons: true

# Logs blocks that burn up in a fire.
block-burn: true

# Logs when a block naturally ignites, such as from fire spreading.
block-ignite: true

# Logs explosions, such as TNT and Creepers.
explosions: true

# Track when an entity changes a block, such as an Enderman destroying blocks.
entity-change: true

# Logs killed entities, such as killed cows and enderman.
entity-kills: true

# Logs text on signs. If disabled, signs will be blank when rolled back.
sign-text: true

# Logs lava and water sources placed/removed by players who are using buckets.
buckets: true

# Logs natural tree leaf decay.
leaf-decay: true

# Logs tree growth. Trees are linked to the player who planted the sappling.
tree-growth: true

# Logs mushroom growth.
mushroom-growth: true

# Logs natural vine growth.
vine-growth: true

# Logs when portals such as Nether portals generate naturally.
portals: true

# Logs water flow. If water destroys other blocks, such as torches,
# this allows it to be properly rolled back.
water-flow: true

# Logs lava flow. If lava destroys other blocks, such as torches,
# this allows it to be properly rolled back.
lava-flow: true

# Allows liquid to be properly tracked and linked to players.
# For example, if a player places water which flows and destroys torches,
# it can all be properly restored by rolling back that single player.
liquid-tracking: true

# Track item transactions, such as when a player takes items from a
# chest, furnace, or dispenser. Necessary for any item based rollbacks.
item-transactions: true

# Track player interactions, such as when a player opens a door, presses
# a button, or opens a chest. Player interactions can't be rolled back.
player-interactions: true

# Logs messages that players send in the chat.
player-messages: true

# Logs all commands used by players.
player-commands: true

# Logs the logins and logouts of players.
player-sessions: true

# Logs when a player changes their Minecraft username.
username-changes: true

# Logs changes made via the plugin "WorldEdit" if it's in use on your server.
worldedit: true
```

**Comment by SBPrime** [comment]
Disable WorldEdit integration. That should solve your problem.
