### ISSUE TITLE
//STACK get error

### ISSUE THREAD

**Issue by tianji1993** [SBPrime/AsyncWorldEdit-Premium#149]
Spigot Version: git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
WorldEdit: worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
https://www.dropbox.com/s/ilvz8yurswp16bb/worldedit-bukkit-7.0.0-SNAPSHOT-dist.zip?dl=0

AsyncWorldEdit - Premium 3.6.0-beta-9

Hi, could someone please help me to handle this issue? use //move //stack //flip will get following error in console, //set can work without error, //paste didn't show error but actully it's not working:

[09:37:01] [Server thread/INFO]: lz666 issued server command: //STACK 8
[09:37:01] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[?:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.getDefaultValue(ParametricCallable.java:382) ~[?:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:230) ~[?:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:210) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:231) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.entity.PlayerWrapper.getCardinalDirection(I)Lcom/sk89q/worldedit/util/Direction;
	at com.sk89q.worldedit.WorldEdit.getPlayerDirection(WorldEdit.java:461) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.getDirection(WorldEdit.java:378) ~[?:?]
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getDirection(WorldEditBinding.java:270) ~[?:?]
	... 35 more

**Comment by SBPrime** [comment]
What version of WE exactly are you using? Could you provide the startup log?
This looks like a mismatched version of WE (to new). I'm currently working on updating to the latest snapshot.

**Comment by tianji1993** [comment]
@SBPrime  WorldEdit: worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
here you can find it: https://www.dropbox.com/s/ilvz8yurswp16bb/worldedit-bukkit-7.0.0-SNAPSHOT-dist.zip?dl=0
it's the latest version I can get from worldedit website.

**Comment by SBPrime** [comment]
Fixed in RC-01
