### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by ecoterrorist** [SBPrime/AsyncWorldEdit-Premium#150]
AsyncWorldEdit is completely broken on my server (1.13.2), and gives this error when WE commands are used. https://hastebin.com/tumucihuno.bash

I have tried about 10 different AWE versions, through October, and tried PaperMC vs. Regular Spigot. Nothing helps, and this always happens.

To troubleshoot I even removed 60+ of my plugins, so that I'm running a totally barebone server... still doesn't work

**Comment by SBPrime** [comment]
```
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:403) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:391) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.getBlock(Spigot_v1_13_R2.java:237) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:445) ~[?:?]
```

This is not an error of AWE, you are using a mismatched version of WE and spigot.
