### ISSUE TITLE
Error With //undo

### ISSUE THREAD

**Issue by winnyok2042** [SBPrime/AsyncWorldEdit-Premium#151]
[Craft Scheduler Thread - 31/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-02 generated an exception while executing task 9651
java.lang.ClassCastException: org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to com.sk89q.worldedit.bukkit.BukkitWorld
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldEditFlagHandler.setBlock(WorldEditFlagHandler.java:38) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:112) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:94) ~[?:?]
	at com.sk89q.worldedit.function.operation.SetLocatedBlocks.resume(SetLocatedBlocks.java:43) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.__0058e670103f45bab19c3cb44ca7dfd4__completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__0058e670103f45bab19c3cb44ca7dfd4__completeBlindly.execute(Unknown Source) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:78) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:670) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.flushSession(ThreadSafeEditSession.java:612) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:87) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:155) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-478]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-478]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-478]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Ver: Paper #478
Worldedit : WorldEdit v7.0.0-beta-03 
Worldguard:  WorldGuard 7.0.0 Beta 2 
Worldguard: WorldGuard Extra Flags 4.1.1

**Comment by SBPrime** [comment]
The version of WorldGuard Extra Flags that you are using is not compatible with awe. From what I was informed you need a beta version.
