### ISSUE TITLE
//copy doesn't work (another error)

### ISSUE THREAD

**Issue by lilian-gnt** [SBPrime/AsyncWorldEdit-Premium#156]
```
[13:56:53 INFO]: HookDonn_ issued server command: //copy
[13:56:53 WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-03 generated an exception while executing task 1083
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:403) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:391) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2.getBlock(Spigot_v1_13_R2.java:237) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:445) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.lambda$getFullBlock$20(AsyncWorld.java:710) ~[?:?]
	at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:641) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getFullBlock(AsyncWorld.java:709) ~[?:?]
	at com.sk89q.worldedit.EditSession.getFullBlock(EditSession.java:482) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doGetFullBlock(ThreadSafeEditSession.java:769) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.lambda$getFullBlock$2(ThreadSafeEditSession.java:513) ~[?:?]
	at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:651) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.getFullBlock(ThreadSafeEditSession.java:513) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.getFullBlock(CancelabeEditSession.java:271) ~[?:?]
	at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:72) ~[?:?]
	at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57) ~[?:?]
	at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.__6877f4b38b73455185f69ecf953d7e01__completeLegacy(Operations.java:55) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__6877f4b38b73455185f69ecf953d7e01__completeLegacy.execute(Unknown Source) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor$1.task(AsyncOperationProcessor.java:163) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

AsyncWorldEdit - Premium 3.6.0-rc-03
worldedit-bukkit-7.0.0-beta-03.jar
worldguard-legacy-7.0.0-beta-02.jar
Spigot : git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by SBPrime** [comment]
Looks like you are using a mismatched version of WE and spigot. Try using beta-04, or dev builds (might crash at startup).

**Comment by lilian-gnt** [comment]
With the beta-04 WorldEdit, it works on the game. We still have an error in the console here:

```
[14:31:24 ERROR]: Failed to save chunk
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1614) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.c(Entity.java:1508) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.Entity.d(Entity.java:1516) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveEntities(ChunkRegionLoader.java:524) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:288) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:333) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:284) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:951) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [server.jar:git-Spigot-29ab5e4-2bc7d1d]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1540) ~[server.jar:git-Spigot-29ab5e4-2bc7d1d]
    ... 13 more
[14:31:37 INFO]: HookDonn_ issued server command: //copy
[14:31:38 INFO]: [AsyncWorldEdit] ***********************************
[14:31:38 INFO]: [AsyncWorldEdit] Error performing safe operation for MineDream1 cx: -52 cz: 33 Loaded: true
[14:31:38 INFO]: [AsyncWorldEdit] ***********************************
[14:31:38 INFO]: [AsyncWorldEdit] *
[14:31:38 INFO]: [AsyncWorldEdit] * Exception: java.lang.NullPointerException
[14:31:38 INFO]: [AsyncWorldEdit] * Error message: null
[14:31:38 INFO]: [AsyncWorldEdit] * Stack:
[14:31:38 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.World.E(World.java:1694)
[14:31:38 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.World.getTileEntity(World.java:1682)
[14:31:38 INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.WorldServer.getTileEntity(WorldServer.java:125)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2_2.getBlock(Spigot_v1_13_R2_2.java:237)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:445)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.lambda$getFullBlock$20(AsyncWorld.java:710)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:641)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getFullBlock(AsyncWorld.java:709)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.getFullBlock(EditSession.java:579)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doGetFullBlock(ThreadSafeEditSession.java:769)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.lambda$getFullBlock$2(ThreadSafeEditSession.java:513)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:651)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.getFullBlock(ThreadSafeEditSession.java:513)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.getFullBlock(CancelabeEditSession.java:271)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:72)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.__81680419cc88494ea55e9c0506669153__completeLegacy(Operations.java:55)
[14:31:38 INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations_InnerForMethod__81680419cc88494ea55e9c0506669153__completeLegacy.execute(Unknown Source)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor$1.task(AsyncOperationProcessor.java:163)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71)
[14:31:38 INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152)
[14:31:38 INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[14:31:38 INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:31:38 INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:31:38 INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:31:38 INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[14:31:38 INFO]: [AsyncWorldEdit] ***********************************
```

**Comment by SBPrime** [comment]
Error performing safe operation is somewhat expected on  paper. In general you can ignore those.  So case closed?

**Comment by lilian-gnt** [comment]
Okay, well yes, it looks like everything is good at once. Thank you.

**Comment by SBPrime** [comment]
Ok, if you have any problems get back to me. You can use spigot. Its usually faster way to communicate.
