### ISSUE TITLE
AsyncWorldEdit error

### ISSUE THREAD

**Issue by andris155** [SBPrime/AsyncWorldEdit-Premium#161]
```
[12:37:23] [Craft Scheduler Thread - 885/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-04 generated an exception while executing task 1851078
java.lang.ClassCastException: class org.primesoft.asyncworldedit.worldedit.world.AsyncWorld cannot be cast to class com.sk89q.worldedit.bukkit.BukkitWorld (org.primesoft.asyncworldedit.worldedit.world.AsyncWorld is in unnamed module of loader org.primesoft.asyncworldedit.LoaderBukkit @7ef70faa; com.sk89q.worldedit.bukkit.BukkitWorld is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4c7d8998)
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldEditFlagHandler.setBlock(WorldEditFlagHandler.java:38) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:80) ~[?:?]
	at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:114) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:94) ~[?:?]
	at com.sk89q.worldedit.function.operation.SetLocatedBlocks.resume(SetLocatedBlocks.java:43) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.__e943db9139064fc7b2de2067e5b9abcc__completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__e943db9139064fc7b2de2067e5b9abcc__completeBlindly.execute(Unknown Source) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:78) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:767) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.flushSession(ThreadSafeEditSession.java:612) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:87) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:372) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:368) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:155) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
	at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-495]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-495]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SBPrime** [comment]
You are using a version of the WG flags that is not compatible with AWE update to latest one.
