### ISSUE TITLE
//undo not work with coreprotect

### ISSUE THREAD

**Issue by jewome62** [SBPrime/AsyncWorldEdit-Premium#165]
With WorldEdit 7 beta 5, AsyncWorldEdit - Premium 3.6.0-rc-05
![image](https://user-images.githubusercontent.com/472429/51870568-44341600-2354-11e9-98ce-fdcde7e00bf6.png)

```
28.01 22:24:19 [Server] INFO jewome62 issued server command: //undo 
28.01 22:24:19 [Server] WARN [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-05 generated an exception while executing task 44 
28.01 22:24:19 [Server] INFO java.lang.AbstractMethodError: Receiver class net.coreprotect.worldedit.CoreProtectLogger does not define or inherit an implementation of the resolved method abstract getBlock(Lcom/sk89q/worldedit/math/BlockVector3;)Lcom/sk89q/worldedit/world/block/BlockState; of interface com.sk89q.worldedit.extent.InputExtent. 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:215) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.history.change.BlockChange.undo(BlockChange.java:89) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.UndoProcessor.resume(UndoProcessor.java:119) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.__d366cf82ea2a4b5fbff067248adef993__completeBlindly(Operations.java:74) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__d366cf82ea2a4b5fbff067248adef993__completeBlindly.execute(Unknown Source) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:82) ~[?:?] 
28.01 22:24:19 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:83) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:392) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:388) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:154) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?] 
28.01 22:24:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349] 
28.01 22:24:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349] 
28.01 22:24:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
28.01 22:24:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 
28.01 22:24:19 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
```

There are something to do into configuration ?

Thanks

**Comment by SBPrime** [comment]
This is a bug in coreprotect. If you want to use coreprotect you need to use blockshub.
