### ISSUE TITLE
//undo generating exception and not working

### ISSUE THREAD

**Issue by hamcoremusic** [SBPrime/AsyncWorldEdit-Premium#167]
When I preform //undo on the latest version of AWE and WE I get this exception....

```
01.02 18:30:37 [Server] INFO HAMCORE issued server command: //undo
01.02 18:30:37 [Server] WARN [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-05 generated an exception while executing task 589
01.02 18:30:37 [Server] INFO java.lang.AbstractMethodError: null
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:215) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.history.change.BlockChange.undo(BlockChange.java:89) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.UndoProcessor.resume(UndoProcessor.java:119) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.__58ce4f9e3c8a44349f8038237eccbdd4__completeBlindly(Operations.java:74) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__58ce4f9e3c8a44349f8038237eccbdd4__completeBlindly.execute(Unknown Source) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:82) ~[?:?]
01.02 18:30:37 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:83) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:392) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:388) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:154) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
01.02 18:30:37 [Server] INFO at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
01.02 18:30:37 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-509]
01.02 18:30:37 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-509]
01.02 18:30:37 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-509]
01.02 18:30:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
01.02 18:30:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
```

**Comment by hamcoremusic** [comment]
Turned block logging on in CoreProtect and this happened. I turned it off and now it's fine!

**Comment by SBPrime** [comment]
Core protect is broken. If you want to use coreprotect you need to DISABLE worldedit integration enable API and get BlocksHub.
