### ISSUE TITLE
/awe cancel error

### ISSUE THREAD

**Issue by andris155** [SBPrime/AsyncWorldEdit-Premium#170]
```
[14:32:27] [Server thread/INFO]: andris155 issued server command: /awe cancel 0
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] ***********************************
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] Unable to delegate extent action.
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] ***********************************
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] *
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Exception: java.lang.IllegalArgumentException
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Error message: org.primesoft.asyncworldedit.utils.SessionCanceled
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Stack: 
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.CancelableWorld.getBlock(CancelableWorld.java:290)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.cache.LastAccessExtentCache.getBlock(LastAccessExtentCache.java:54)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.lambda$getBlock$2(SafeDelegateExtent.java:137)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.safeDelegate(SafeDelegateExtent.java:90)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.getBlock(SafeDelegateExtent.java:137)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:88)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.SetLocatedBlocks.resume(SetLocatedBlocks.java:43)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly(Operations.java:74)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations_InnerForMethod__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly.execute(Unknown Source)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:82)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.flushSession(EditSession.java:767)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.forceFlush(CancelabeEditSession.java:439)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:348)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.setBlock(EditSession.java:658)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:361)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly(Operations.java:74)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations_InnerForMethod__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly.execute(Unknown Source)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor$2.task(AsyncOperationProcessor.java:223)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.lang.Thread.run(Thread.java:834)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] *
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Exception: org.primesoft.asyncworldedit.utils.SessionCanceled
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Error message: null
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * Stack: 
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.CancelableWorld.getBlock(CancelableWorld.java:290)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.cache.LastAccessExtentCache.getBlock(LastAccessExtentCache.java:54)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.lambda$getBlock$2(SafeDelegateExtent.java:137)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.safeDelegate(SafeDelegateExtent.java:90)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.SafeDelegateExtent.getBlock(SafeDelegateExtent.java:137)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.extent.AbstractDelegateExtent.getBlock(AbstractDelegateExtent.java:70)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.extent.inventory.FixedBlockBagExtent.setBlock(FixedBlockBagExtent.java:88)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.SetLocatedBlocks.resume(SetLocatedBlocks.java:43)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:89)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly(Operations.java:74)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations_InnerForMethod__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly.execute(Unknown Source)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:178)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:82)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.flushSession(EditSession.java:767)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.forceFlush(CancelabeEditSession.java:439)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:348)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.setBlock(EditSession.java:658)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.setBlock(CancelabeEditSession.java:361)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations.__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly(Operations.java:74)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations_InnerForMethod__c0d4201fe4cb4ca1b5531af6f1d1c636__completeBlindly.execute(Unknown Source)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor$2.task(AsyncOperationProcessor.java:223)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:152)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] * java.base/java.lang.Thread.run(Thread.java:834)
[14:32:27] [Craft Scheduler Thread - 1191/INFO]: [AsyncWorldEdit] ***********************************
[14:32:27] [Craft Scheduler Thread - 1191/WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.0-rc-05 generated an exception while executing task 2386798
java.lang.IllegalArgumentException: org.primesoft.asyncworldedit.utils.SessionCanceled
	at org.primesoft.asyncworldedit.worldedit.world.CancelableWorld.commit(CancelableWorld.java:335) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
	at com.sk89q.worldedit.EditSession.commit(EditSession.java:772) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:767) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.flushSession(CancelabeEditSession.java:426) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:168) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-527]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-527]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-527]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.primesoft.asyncworldedit.utils.SessionCanceled
	... 29 more
```

**Comment by SBPrime** [comment]
This is by design.
