### ISSUE TITLE
Error on run Server 

### ISSUE THREAD

**Issue by BearLeon** [SBPrime/AsyncWorldEdit-Premium#173]
Server : git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
AsyncWorldEdit-Premium : v3.6.0-rc-05
WorldEdit :7.0.0 Build #4118
[08:42:36 ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] null initializing AsyncWorldEdit v3.6.0-rc-05 (Is it up to date?)
java.lang.NullPointerException: null
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:283) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:334) ~[patched_1.13.2.jar:git-Paper-500]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-500]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-500]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by SBPrime** [comment]
You need to provide the full server startup log.

**Comment by BearLeon** [comment]
[22:47:36] [main/INFO]: Loaded 0 recipes
[22:47:36] [Server thread/INFO]: Starting minecraft server version 1.13.2
[22:47:36] [Server thread/INFO]: Loading properties
[22:47:36] [Server thread/INFO]: Default game type: SURVIVAL
[22:47:36] [Server thread/INFO]: This server is running Paper version git-Paper-"0181fb14" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[22:47:36] [Server thread/INFO]: Debug logging is disabled
[22:47:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:47:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:47:36] [Server thread/INFO]: Generating keypair
[22:47:36] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:47:36] [Server thread/INFO]: Using default channel type
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Injector platform set to: InjectorBukkit
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Injecting WorldEdit classes...
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector2
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.BlockVector3
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector2
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.math.Vector3
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockStateHolder
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BaseBlock
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.block.BlockState
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.entity.BaseEntity
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.util.Location
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Modiffy class com.sk89q.worldedit.world.biome.BaseBiome
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] *
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.io.IOException
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Class not found
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * Stack: 
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.readStream(ClassReader.java:261)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.lib.org.objectweb.asm.ClassReader.<init>(ClassReader.java:234)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.ClassInjectorBukkit.getClassReader(ClassInjectorBukkit.java:121)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:248)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:180)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:237)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:96)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Class.forName(Unknown Source)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Unknown Source)
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] Unable to initialize injector.
[22:47:40] [Server thread/INFO]: [AsyncWorldEdit] ERROR: Unable to enable the injector.
[22:47:40] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.0.0-SNAPSHOT;4129-ec0422d
[22:47:41] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@5b010289]
[22:47:41] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2_2 as the Bukkit adapter
[22:47:41] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.6.0-rc-05
[22:47:41] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] null initializing AsyncWorldEdit v3.6.0-rc-05 (Is it up to date?)
java.lang.NullPointerException: null
	at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:283) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336) ~[Paper-1.13.2-0181fb1-20190409-0408.jar:git-Paper-"0181fb14"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[Paper-1.13.2-0181fb1-20190409-0408.jar:git-Paper-"0181fb14"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[Paper-1.13.2-0181fb1-20190409-0408.jar:git-Paper-"0181fb14"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[22:47:41] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.0-SNAPSHOT;1839-5ffade9
[22:47:41] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:47:41] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.6.0-rc-05
[22:47:42] [Server thread/INFO]: Preparing level "world"
[22:47:42] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[22:47:43] [Server thread/INFO]: Loaded 524 recipes
[22:47:43] [Server thread/INFO]: -------- World Settings For [world] --------
[22:47:43] [Server thread/INFO]: Mob Spawn Range: 8
[22:47:43] [Server thread/INFO]: Cactus Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Cane Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Melon Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Sapling Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Carrot Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Potato Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Wheat Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Vine Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[22:47:43] [Server thread/INFO]: Experience Merge Radius: 3.0
[22:47:43] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:47:43] [Server thread/INFO]: Random Lighting Updates: false
[22:47:43] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[22:47:43] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:47:43] [Server thread/INFO]: Max TNT Explosions: 100
[22:47:43] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:47:43] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[22:47:43] [Server thread/INFO]: View Distance: 10
[22:47:43] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:47:43] [Server thread/INFO]: Arrow Despawn Rate: 1200
[22:47:43] [Server thread/INFO]: Item Despawn Rate: 6000
[22:47:43] [Server thread/INFO]: Item Merge Radius: 2.5
[22:47:43] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:47:43] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[22:47:44] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[22:47:44] [Server thread/INFO]: Mob Spawn Range: 8
[22:47:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Carrot Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Potato Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[22:47:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:47:44] [Server thread/INFO]: Random Lighting Updates: false
[22:47:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[22:47:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:47:44] [Server thread/INFO]: Max TNT Explosions: 100
[22:47:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:47:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[22:47:44] [Server thread/INFO]: View Distance: 10
[22:47:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:47:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[22:47:44] [Server thread/INFO]: Item Despawn Rate: 6000
[22:47:44] [Server thread/INFO]: Item Merge Radius: 2.5
[22:47:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:47:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[22:47:44] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[22:47:44] [Server thread/INFO]: Mob Spawn Range: 8
[22:47:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Carrot Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Potato Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[22:47:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[22:47:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:47:44] [Server thread/INFO]: Random Lighting Updates: false
[22:47:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[22:47:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:47:44] [Server thread/INFO]: Max TNT Explosions: 100
[22:47:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:47:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[22:47:44] [Server thread/INFO]: View Distance: 10
[22:47:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:47:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[22:47:44] [Server thread/INFO]: Item Despawn Rate: 6000
[22:47:44] [Server thread/INFO]: Item Merge Radius: 2.5
[22:47:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[22:47:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[22:47:44] [Server thread/INFO]: Preparing start region for level minecraft:overworld (Seed: 1766717370021189414)
[22:47:44] [Server thread/INFO]: Preparing start region for level minecraft:the_nether (Seed: 1766717370021189414)
[22:47:44] [Server thread/INFO]: Preparing start region for level minecraft:the_end (Seed: 1766717370021189414)
[22:47:44] [Server thread/INFO]: Time elapsed: 28 ms
[22:47:44] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-SNAPSHOT;4129-ec0422d
[22:47:44] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[22:47:44] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[22:47:44] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.0-SNAPSHOT;1839-5ffade9
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\config.yml
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world\config.yml
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world\blacklist.txt
[22:47:44] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world_nether\config.yml
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world_nether\blacklist.txt
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world_the_end\config.yml
[22:47:44] [Server thread/INFO]: [WorldGuard] Default configuration file written: C:\Users\BearLeonLight\Desktop\McServer (1.13.2)\plugins\WorldGuard\worlds\world_the_end\blacklist.txt
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[22:47:44] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[22:47:44] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[22:47:44] [Server thread/INFO]: [WorldGuard] Loading region data...
[22:47:44] [Server thread/INFO]: [WorldGuard] Unloading and saving region data that is currently loaded...
[22:47:44] [Server thread/INFO]: [WorldGuard] Loading region data for loaded worlds...
[22:47:44] [Server thread/INFO]: [WorldGuard] Loading region data...
[22:47:44] [Server thread/INFO]: [WorldGuard] Regions saved after UUID migration! This won't happen again unless you change the relevant configuration option in WorldGuard's config.
[22:47:44] [Server thread/INFO]: Done (2.031s)! For help, type "help"
[22:47:44] [Server thread/INFO]: Timings Reset
[22:47:55] [User Authenticator #1/INFO]: UUID of player BearLeon is a52e1ae6-724c-48b3-9384-fe12b3299407
[22:47:55] [Server thread/INFO]: BearLeon[/192.168.50.122:1879] logged in with entity id 122 at ([world]73.5, 65.0, 178.5)

**Comment by BearLeon** [comment]
I am here to catch the development version.
http://builds.enginehub.org/job/worldedit/11228

**Comment by SBPrime** [comment]
You need to use the supported version of WE (currently snapshots are not supported).
