### ISSUE TITLE
Issue when using //undo

### ISSUE THREAD

**Issue by liljayp** [SBPrime/AsyncWorldEdit-Premium#186]
After using the command //brush sphere stone 5 and then trying to //undo the operation doesn't complete. 

Server Version: Paper 135 (1.14.4)
AsyncWorldEdit Version: 3.6.7
WorldEdit Version:  worldedit-bukkit-7.0.1-SNAPSHOT 

```
liljayp issued server command: //brush sphere stone 5
[13:18:03 INFO]: liljayp issued server command: //undo
[13:18:03 WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.7 generated an exception while executing task 1026
java.lang.NullPointerException: null
        at com.sk89q.worldedit.util.collection.LocatedBlockList.get(LocatedBlockList.java:70) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.lambda$getBufferedBlock$12(MultiStageReorder.java:258) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_211]
        at java.util.HashMap$ValueSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
        at java.util.stream.ReferencePipeline.findAny(Unknown Source) ~[?:1.8.0_211]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.getBufferedBlock(MultiStageReorder.java:260) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractBufferingExtent.getBlock(AbstractBufferingExtent.java:54) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.setBlock(MultiStageReorder.java:223) ~[?:?]
        at com.sk89q.worldedit.history.change.BlockChange.undo(BlockChange.java:89) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.UndoProcessor.resume(UndoProcessor.java:119) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.__9d7d8011b5fd4d6fabe97f7a86c3fd03__completeBlindly(Operations.java:74) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__9d7d8011b5fd4d6fabe97f7a86c3fd03__completeBlindly.execute(Unknown Source) ~[?:?]
        at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:181) ~[?:?]
        at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:87) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.UndoProcessor.processUndo(UndoProcessor.java:83) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.doUndo(CancelabeEditSession.java:415) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.undo(CancelabeEditSession.java:411) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.AsyncEditSession$1.task(AsyncEditSession.java:154) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:71) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:160) ~[?:?]
        at org.primesoft.asyncworldedit.utils.SchedulerUtils.processTaskQueue(SchedulerUtils.java:168) ~[?:?]
        at org.primesoft.asyncworldedit.utils.SchedulerUtils.access$000(SchedulerUtils.java:62) ~[?:?]
        at org.primesoft.asyncworldedit.utils.SchedulerUtils$1.run(SchedulerUtils.java:131) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-135]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-135]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[13:18:46 INFO]: liljayp issued server command: /awe jobs
```

**Comment by liljayp** [comment]
Just tried it without AsyncWorldEdit installed and //undo works correctly.

**Comment by SBPrime** [comment]
You need to use WorldEdit from here:
https://dev.bukkit.org/projects/worldedit/files

I do not support snapshot versions. Some snapshots might work some might not.

**Comment by SBPrime** [comment]
Added compatibility for WE 7.0.1 in 3.6.8
