### ISSUE TITLE
//regen does not work

### ISSUE THREAD

**Issue by SFTMedia** [SBPrime/AsyncWorldEdit-Premium#190]
//regen does not work for me.
Currently using AsyncWorldEdit 3.6.8 and WorldEdit 7.0.1 snapshot 4576.
For me, regen did not work even with previous versions in MC 1.14.
It just says it is regenerating, but nothing happens.

https://gyazo.com/70b28ef45907b5d638cb750a4d6ecc9b

**Comment by SBPrime** [comment]
Without the server log I can't help.

**Comment by SFTMedia** [comment]
That's the thing, there is no error in the console, there is no sign of anything not working, it just says processing then nothing happens.

**Comment by SBPrime** [comment]
Then please set the AWE log level to debug do the regen command an send me the server log starting for when you executed the command.

**Comment by SFTMedia** [comment]
[11:52:27] [Server thread/WARN]: Chunk generation via Bukkit raised an error
java.lang.UnsupportedOperationException: Not supported in this Minecraft version! Unless you can fix it, this is not a bug :)
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.regenerateChunk(CraftWorld.java:471) ~[patched_1.14.4.jar:git-Paper-148]
	at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:191) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerateChunk(RegionCommands.java:365) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration._regen(RegionCommandsRegistration.java:555) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:471) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:105) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:499) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:341) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-148]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-148]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-148]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]


I can provide the full log if needed, but this should clarify. I am not sure why it is not supported, hoping you know that :)

**Comment by SBPrime** [comment]
```[11:52:27] [Server thread/WARN]: Chunk generation via Bukkit raised an error
java.lang.UnsupportedOperationException: Not supported in this Minecraft version! Unless you can fix it, this is not a bug :)
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.regenerateChunk(CraftWorld.java:471) ~[patched_1.14.4.jar:git-Paper-148]
at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:191) ~[?:?]```

This is no a bug of AWE nor WE its lack of support for regen in the version of the server that you are using.
