### ISSUE TITLE
//set problem

### ISSUE THREAD

**Issue by favorit5503** [SBPrime/AsyncWorldEdit-Premium#194]
I got this problem recently. I cannot //set nothing. It throws an error. But //Copy //paste //replace is working only the //set has some problems.
My log: https://pastebin.com/qyiiiWzg
I have WE 7.0.1
I have AWE Premium 3.6.11
Spigot username : Favorit5503

Thank you!

**Comment by SBPrime** [comment]
Please enable debug in awe and send me the log for the operation that failed.

**Comment by favorit5503** [comment]
you can donwload it here i hope it helps
http://valenserver.eu/download/latest.log

**Comment by SBPrime** [comment]
Error is caused by lack of support for AWE in me.lucko.luckperms.common.model.UserIdentifier
I'm going to add a workaround in next release.

**Comment by favorit5503** [comment]
Thank you :)

**Comment by SBPrime** [comment]
Added option to customize class scanner in 3.6.12

**Comment by favorit5503** [comment]
Hi. I tried the solution but it dosnt work. I added luckperms to the class scanner blacklist and now i got an another error

[11:19:40] [Server thread/INFO]: Favorit5503 issued server command: //set 0
[11:19:42] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: misformatted DER value
	at sun.security.util.DerValue.toString(Unknown Source) ~[?:1.8.0_231]
	at sun.security.util.DerValue.hashCode(Unknown Source) ~[?:1.8.0_231]
	at java.util.HashMap.hash(Unknown Source) ~[?:1.8.0_231]
	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_231]
	at java.util.HashSet.add(Unknown Source) ~[?:1.8.0_231]
	at org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.scan(ClassScanner.java:243) ~[?:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:188) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:85) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:777) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.flushSession(ThreadSafeEditSession.java:634) ~[?:?]
	at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:306) ~[?:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:903) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.createEditSession(WrappedLocalSession.java:156) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_231]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:243) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
	at java.util.Optional.flatMap(Unknown Source) ~[?:1.8.0_231]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_231]
	at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
	at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
	at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.editSession(RegionCommandsRegistration.java:730) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration._set(RegionCommandsRegistration.java:399) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:471) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:105) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:496) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:341) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by SBPrime** [comment]
Did you customize the class scanner? Please send me the config.

**Comment by favorit5503** [comment]
Yes i did change. Here is the config.
http://pastebin.com/qRn3ACuF

**Comment by SBPrime** [comment]
Set the log level to debug, use the set command and send me the logs.

**Comment by favorit5503** [comment]
Here you goo 

https://pastebin.com/4nVRqjCg

**Comment by favorit5503** [comment]
But its set to INFO becouse if i set it to DEBUG my hole console is continously spamming the console and the server crashing.

**Comment by SBPrime** [comment]
The data needed to configure the plugin is available only when you enable debug. If it crashes when you enable debug you can send that log.

**Comment by favorit5503** [comment]
You can download it here becouse its to big: http://valenserver.eu/download/log.gz

**Comment by SBPrime** [comment]
"Sorry! We couldn't find that page."

**Comment by favorit5503** [comment]
I tried it works. It will automaticaly download the log

**Comment by SBPrime** [comment]
Now it worked. You are using lands which is not compatible with AWE, please add: 
me.angeschossen.lands.integration.manager.worldedit.WorldEdit: {}
me.angeschossen.lands.c.a.l: {}

and try again.

**Comment by favorit5503** [comment]
Yep now it works thank you.
