### ISSUE TITLE
Cancel Jobs

### ISSUE THREAD

**Issue by StarozytnySky** [SBPrime/AsyncWorldEdit-Premium#197]
Server version: 1.14.4 build 225
Plugin version: 3.6.14

[18:42:03 INFO]: Pancerny issued server command: /awe cancel 0
[18:42:03 WARN]: [AsyncWorldEdit] Plugin AsyncWorldEdit v3.6.14 generated an exception while executing task 4073
java.lang.IllegalArgumentException: org.primesoft.asyncworldedit.utils.SessionCanceled
at org.primesoft.asyncworldedit.worldedit.world.CancelableWorld.commit(CancelableWorld.java:336) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.commit(AbstractDelegateExtent.java:126) ~[?:?]
at com.sk89q.worldedit.EditSession.commit(EditSession.java:782) ~[?:?]
at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:777) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.flushSession(CancelabeEditSession.java:454) ~[?:?]
at org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:176) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-225]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-225]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-225]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.primesoft.asyncworldedit.utils.SessionCanceled
... 23 more

**Comment by SBPrime** [comment]
This is by design. There are no plans to change this.
