### ISSUE TITLE
Newest AWE 3.7.0 breaks //move -a and //stack -a

### ISSUE THREAD

**Issue by craftyfoxe** [SBPrime/AsyncWorldEdit-Premium#225]
The newest AWE 3.7.0 breaks //move -a and //stack -a so that they don't work anymore.

![2020-05-11_12 54 53](https://user-images.githubusercontent.com/48233056/81589094-280c8a80-9387-11ea-97ef-6d287d645ae1.png)

```
11.05 16:55:40 [Server] Server thread/INFO CraftyFoxe issued server command: //move 2 -a
11.05 16:55:40 [Server] Server thread/ERROR An unexpected error while handling a WorldEdit command
11.05 16:55:40 [Server] INFO java.lang.AbstractMethodError: null
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.injectEditSession(AsyncOperationProcessor.java:326) ~[?:?]
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:156) ~[?:?]
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethodEx(Helpers.java:96) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.EditSession.moveRegion(EditSession.java:1358) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.command.RegionCommands.move(RegionCommands.java:331) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_move(RegionCommandsRegistration.java:540) ~[?:?]
11.05 16:55:40 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
11.05 16:55:40 [Server] INFO at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source) ~[?:?]
11.05 16:55:40 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
11.05 16:55:40 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:107) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:71) ~[?:?]
11.05 16:55:40 [Server] INFO at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:496) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
11.05 16:55:40 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
11.05 16:55:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
11.05 16:55:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by Tsoccerguy3** [comment]
running ASWE PRE 3.7
             WorldEdit 7.2 Build #5003
              Paper 1.15.2 b 280
No issues

**Comment by SBPrime** [comment]
@craftyfoxe Please provide:
* java version,
* server startup log,
* log for 1block operation (move or stack) with AWE debug level set to debug.

**Comment by craftyfoxe** [comment]
Java edition 1.15.2
https://pastebin.com/fuYiBeRz
^This has startup log 
https://pastebin.com/DKVjv9nh
^This is with debug set to debug

I just tested this on my private server and it gets the same error

**Comment by Tsoccerguy3** [comment]
crafty can you try with the latest WE 7.2 build and latest paper build . check to see if it runs without error

**Comment by Tsoccerguy3** [comment]
running that command on WE 7.1 https://timings.aikar.co/?id=1cfcdeeca44e464a94c7f33c2e749971#plugins

ASWE is using a lot of TPS and memory slowly max's out

**Comment by craftyfoxe** [comment]
> crafty can you try with the latest WE 7.2 build and latest paper build . check to see if it runs without error

Isn't that latest version of Worldedit 7.1.0? I don't see a 7.2 on bukkit

**Comment by Tsoccerguy3** [comment]
All current Worldedit ,Worldgard , etc https://builds.enginehub.org/
Paper https://papermc.io/downloads

**Comment by Tsoccerguy3** [comment]
Update ASWE 3.7.1 no longer works with WE 7.2 branch

**Comment by SBPrime** [comment]
This issue was originally about broken move, it was caused by an error in injector, problem was already fixed.
Thew WE 7.2 is not related.
