### ISSUE TITLE
Add support for WorldEdit version 6.1.1-SNAPSHOT;3406-0e200df5

### ISSUE THREAD

**Issue by mibby** [SBPrime/AsyncWorldEdit-Premium#24]
AsyncWorldEdit version 3.2.2
AsyncWorldEditInjector version 3.2.2
WorldEdit version 6.1.1-SNAPSHOT;3406-0e200df5

Assuming latest worldedit dev build broke with AsyncWorldEdit due to the command changes?

```
[04:16:00] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.2.2
[04:16:00] [Server thread/INFO]: [AsyncWorldEdit] BlocksHub plugin not found.
[04:16:00] [Server thread/INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix.
[04:16:00] [Server thread/INFO]: [AsyncWorldEditInjector] New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
[04:16:00] [Server thread/ERROR]: Error occurred while enabling AsyncWorldEdit v3.2.2 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldedit.util.command.SimpleDescription.setDescription(Ljava/lang/String;)V
    at org.primesoft.asyncworldedit.excommands.CommandsInjector.createGroup(CommandsInjector.java:166) ~[?:?]
    at org.primesoft.asyncworldedit.excommands.CommandsInjector.injectCommands(CommandsInjector.java:96) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.WorldeditIntegrator.<init>(WorldeditIntegrator.java:117) ~[?:?]
    at org.primesoft.asyncworldedit.AsyncWorldEditMain.onEnable(AsyncWorldEditMain.java:291) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

```
[04:18:10] [Server thread/INFO]: mibby issued server command: /we
[04:18:10] [Server thread/ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@2a72a6e2 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    ... 19 more
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Ljava/lang/Object;
    at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    ... 19 more
```

```
[04:18:12] [Server thread/INFO]: mibby issued server command: //wand
[04:18:12] [Server thread/ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@30d1ed31 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-5be55c3-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    ... 19 more
Caused by: java.lang.AbstractMethodError: org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(Ljava/lang/String;Lcom/sk89q/minecraft/util/commands/CommandLocals;[Ljava/lang/String;)Ljava/lang/Object;
    at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar:?]
    ... 19 more
```

**Comment by SBPrime** [comment]
As a rule I support only the versions published on dev bukkit. Are there any critical features/changes that require you to update to the latest snapshot of worldedit?

**Comment by mibby** [comment]
Not specifically. I just like to stay up to date with dev source changes to test new features / fixes / optimizations. The new brush commands in the newer dev builds for example are very interesting to play around with.

**Comment by SBPrime** [comment]
Ok as I said on the forum, I'll push a fix when I figure a nice and clean solution that works for the newest and the old versions. For now use the older version of WE.

**Comment by YellowZaki** [comment]
Yes, there is a critical bugfix in worldedit 6.1.1. The entity paste.
