### ISSUE TITLE
java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by sandboxgamer92** [SBPrime/AsyncWorldEdit-Premium#243]
Hallo,

was meint der Server damit?

[20:04:49] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R2.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R2.IChatBaseComponent, net.minecraft.server.v1_16_R2.ChatMessageType)
[20:04:49] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[20:04:49] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Unknown Source)
[20:04:49] [Server thread/WARN]: 	at com.connorlinfoot.actionbarapi.ActionBarAPI.sendActionBar(ActionBarAPI.java:79)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.progressDisplay.ActionBarAPIIntegrator.setMessage(ActionBarAPIIntegrator.java:135)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.progressDisplay.ProgressDisplayManager.setMessage(ProgressDisplayManager.java:119)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.setBar(BlockPlacer.java:1122)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.showProgress(BlockPlacer.java:1163)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:391)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:95)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:281)
[20:04:49] [Server thread/WARN]: 	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:86)
[20:04:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
[20:04:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[20:04:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059)
[20:04:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349)
[20:04:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007)
[20:04:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846)
[20:04:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[20:04:49] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

Vielen Dank für die Hilfe.

Gruß

Patrick Bronke

**Comment by sandboxgamer92** [comment]
Hello,

did not you have an answere for me?

**Comment by SBPrime** [comment]
`[20:04:49] [Server thread/WARN]: at com.connorlinfoot.actionbarapi.ActionBarAPI.sendActionBar(ActionBarAPI.java:79)`

Error not caused by my plugin, you are using an incompatible action bar. Contact the plugin author.
