### ISSUE TITLE
Planified support on Java 16 OpenJ9 ? (AWE don't start)

### ISSUE THREAD

**Issue by Chevels** [SBPrime/AsyncWorldEdit-Premium#252]
Hello,

After some tests I noticed that AsynchWorldEdit Premium (paid on Spigot with same username) does not work with Java 16 OpenJ9. It only works with "classic" Java 16.
Since Java 16 OpenJ9 is much better for large servers (Java 16 is a disaster and is almost unusable with 1.17), are you thinking of making AWE compatible with this version of Java ? Out of my 68 plugins it is the only one that does not support Java 16 OpenJ9 :/

With OpenJ9 plugin don't start with this error : 

> 21:44:28] [Server thread/INFO]: [AsyncWorldEdit] Detected Java 8+, trying to open modules for reflection access...
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] ***********************************
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] Error opening modules.
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] ***********************************
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] *
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.lang.NullPointerException
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Cannot invoke "java.lang.Object.getClass()" because "obj" is null
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * Stack:
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * java.base/java.lang.reflect.Method.invoke(Method.java:560)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.Reflection.openModuleAccess(Reflection.java:138)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.Reflection.<clinit>(Reflection.java:85)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.utils.ClassLoaderHelper.injectFakePlugin(ClassLoaderHelper.java:175)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:90)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * java.base/java.lang.Class.forNameImpl(Native Method)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * java.base/java.lang.Class.forName(Class.java:422)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.MinecraftServer$$Lambda$3774/0x000000000d9e2110.run(Unknown Source)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] * java.base/java.lang.Thread.run(Thread.java:883)
[21:44:28] [Server thread/INFO]: [AsyncWorldEdit] ***********************************
[21:44:28] [Server thread/ERROR]: Could not load 'plugins/AsyncWorldEdit-3.9.1 (mc 1.13-1.17.1 WE 2.5).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at net.minecraft.server.MinecraftServer$$Lambda$3774/0x000000000d9e2110.run(Unknown Source) [server.jar:3232-Spigot-3c1fc60-cbd747a]
at java.lang.Thread.run(Thread.java:883) [?:?]
Caused by: java.lang.ExceptionInInitializerError
at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
at java.lang.Class.forNameImpl(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:422) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
... 8 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @b5aa2a48
at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
at org.primesoft.asyncworldedit.utils.Reflection.invoke(Reflection.java:181) ~[?:?]
at org.primesoft.asyncworldedit.Loader.findLoadedClass(Loader.java:251) ~[?:?]
at org.primesoft.asyncworldedit.Loader.loadClass(Loader.java:173) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.createInjector(AsyncWorldEditBukkit.java:338) ~[?:?]
at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:228) ~[?:?]
at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:95) ~[?:?]
at java.lang.Class.forNameImpl(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:422) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3232-Spigot-3c1fc60-cbd747a]
... 8 more

Thank for your work !

**Comment by Chevels** [comment]
Here my OpenJ9 version as SBPrime asked me on Spigot : 

openjdk version "16.0.2" 2021-07-20
IBM Semeru Runtime Open Edition 16.0.2.0 (build 16.0.2+7)
Eclipse OpenJ9 VM 16.0.2.0 (build openj9-0.27.0, JRE 16 Linux amd64-64-Bit Compressed References 20210729_69 (JIT enabled, AOT enabled)
OpenJ9 - 1851b0074
OMR - 9db1c870d
JCL - 34df42439f3 based on jdk-16.0.2+7)

**Comment by SBPrime** [comment]
Fixed.
