### ISSUE TITLE
1.9 dev version still trying to use 1.8.0_74?

### ISSUE THREAD

**Issue by leasoncre** [SBPrime/AsyncWorldEdit-Premium#40]
loaded up worldedit (and async) in my 1.9 test server (win7 host machine)
and i receive these errors on server start/launch:
previous dev version of worldedit still functioned (with errors everywhere) but this one says worldedit is loaded (green in /pl), but no worldedit commands exist, they all say 'unknown command'

//-------ver info:----//
WorldEdit version 6.1.1-SNAPSHOT;3458-6c03eea (from ~4hours ago on the dev builds page)

This server is running CraftBukkit version git-Spigot-3104eb1-bf43ca6 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
You are running the latest version

Plugins (29): AsyncWorldEditInjector, CoreProtect, PlayerHeads, OpenInv, GroupManager, Chairs, ActionBarAPI, ProtocolLib, VoxelSniper, BlocksHub, mcMMO, Vault, BlocksHub-CoreProtect, Titlebar, Essentials, HolographicDisplays, LWC, Citizens, AsyncWorldEdit, AsyncWorldEdit-ActionBarAPI, EssentialsProtect, EssentialsChat, ServerSigns, SuperVanish, EssentialsSpawn, WorldEdit, Sentry, WorldGuard, BlocksHub-WorldGuard

Fresh install/compile of spigot/server, no configs have been modified.
//-----error logs----//
[23:31:23] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.1-SNAPSHOT;3458-6c03eea
[23:31:23] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.1-SNAPSHOT;3458-6c03eea (Is it up to date?)
java.lang.ExceptionInInitializerError
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:98) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: Replacing commands is currently undefined behavior
    at com.sk89q.worldedit.util.command.SimpleDispatcher.registerCommand(SimpleDispatcher.java:64) ~[?:?]
    at com.sk89q.worldedit.util.command.fluent.DispatcherNode.register(DispatcherNode.java:71) ~[?:?]
    at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:153) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:86) ~[?:?]
    at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
    at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
    ... 12 more 
//(the 12 more does not display in log file)//

i'd assume the accompanying async error is related to this error (pretty much same error by the looks of it)

groupmanager also has a similar error (might be the same one) could this be a bug in spigot itself? (guessing because of the "at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]" line exists in all of the errors)

thanks for the awesome support and plugin(s)!

**Comment by leasoncre** [comment]
REMOVE THIS, accadentally posed this here by accident. meant to post on main worldedit bug tracker.
apologies.
however, if this does help async, power to ya.

**Comment by SBPrime** [comment]
Few things:
1. When you report an issue to WorldEdit guys and you have AWE installed you will, in 99%, receive a answer: we do not support modified version bla bla bla.
2. The error is caused by AWE setup error.

What happened: you mismatched the WorldEdit version and AWE version. Looks like you are using AsyncWorldEdit and WorldEdit dev. You need to use the AsyncWorldEdit-dev.jar instead of AsyncWorldEdit.jar (you can find it on the version hisory). Replace the main plugin file with the proper one, remove the AsyncWorldEditInjector, restart the server. If after restart you still have problems try a second restart (restart, not reload!) because sometimes the injector does not kick in when you install it for the first time.

**Comment by leasoncre** [comment]
i am useing the -dev jar

Thought, does the injector jar need to be updated as well? [if so, where do i dl it?]
or blocks hub?

**Comment by SBPrime** [comment]
Then simply remove AWE injector and do a clean restart. The problem you reported is caused by mismatched injector and worldedit version.

**Comment by leasoncre** [comment]
i thought the injector jar came seperate. was unaware this version extracted it from the async jar now. thanks!

--fixed, closed--

**Comment by leasoncre** [comment]
is there an update to the AsyncWorldEdit-ActionBarAPI.jar yet? [i can't find it]

**Comment by SBPrime** [comment]
The bridge plugins are extracted into /plugins/AsyncWorldEdit/plugins you need to change the extension from dis to jar to enable a plugin that you want.
