### ISSUE TITLE
AsyncWorldedit API Error

### ISSUE THREAD

**Issue by Foorcee** [SBPrime/AsyncWorldEdit-Premium#42]
`[16:29:40] [Server thread/WARN]: [AsyncWorldEdit] Task #142749 for AsyncWorldEdit v3.2.3 generated an exception
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_66]
    at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_66]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.onJobRemoved(BlockPlacer.java:1116) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.removeJob(BlockPlacer.java:1055) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.entries.JobEntry.process(JobEntry.java:286) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:438) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:365) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:77) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:255) ~[?:?]
    at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:81) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-3f3c65f]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-3f3c65f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-3f3c65f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-3f3c65f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-3f3c65f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-3f3c65f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

**while placing Schematic (my code)**

`        public Integer execute(ICancelabeEditSession editSession) throws MaxChangedBlocksException {
            try {

```
            Collection<BaseBlock> blocks = new ArrayList<>();

            for(Material m : Material.values()){
                if(m != Material.AIR){
                    blocks.add(new BaseBlock(m.getId(), -1));
                }
            }

            Extent ex = editSession.getSurvivalExtent();

            ClipboardReader reader = ClipboardFormat.SCHEMATIC.getReader(new FileInputStream(file.getFile()));
            WorldData worldData = bukkitWorld.getWorldData();
            Clipboard clipboard = reader.read(worldData);
            ClipboardHolder holder = new ClipboardHolder(clipboard, worldData);
            editSession.enableQueue();
            editSession.setFastMode(true);
            editSession.setMask(new BlockMask(ex, blocks));
            Vector to = new Vector(point.getX(), file.getPasteY(), point.getZ());
            final Operation operation = holder
                    .createPaste(editSession, worldData)
                    .to(to)
                    .ignoreAirBlocks(true)
                    .build();
            Operations.completeBlindly(operation);
            editSession.flushQueue();
        } catch (IOException e) {
            System.out.println("Error trying to paste " + file.getName());
        }
        return 32768;
    }`
```

**Comment by SBPrime** [comment]
First of all you are not using the latest version of the plugin.

Second the code you provided has nothing to do with the error

Third, I assume that you are removing a job listener when you get jobRemoved inside the same thread, you simply can't do that.

**Comment by SBPrime** [comment]
Any update?
