### ISSUE TITLE
Unable to use AsyncWorldEdit 3.3.0

### ISSUE THREAD

**Issue by U1F984** [SBPrime/AsyncWorldEdit-Premium#44]
Server starts with this error:

```
[14:18:48 INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.3.0
[14:18:48 WARN]: [AutoSaveWorld] Plugin AsyncWorldEdit attempted to establish connection http://www.spigotmc.org/api/resource.php?user_id=22176&resource_id=9661once=321311524 in main server thread
[14:18:48 WARN]: [AutoSaveWorld] Plugin AsyncWorldEdit attempted to establish connection socket://www.spigotmc.org:80 in main server thread
[14:18:48 INFO]: [AsyncWorldEditInjector] Injector platform set to: Manual
[14:18:48 INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[14:18:48 INFO]: [AsyncWorldEditInjector] ****************************
[14:18:48 INFO]: [AsyncWorldEditInjector] * CLASS INJECTION FAILED!! *
[14:18:48 INFO]: [AsyncWorldEditInjector] ****************************
[14:18:48 INFO]: [AsyncWorldEditInjector] * AsyncWorldEdit won't work properly.
[14:18:48 INFO]: [AsyncWorldEditInjector] * Exception: java.lang.NoSuchMethodError
[14:18:48 INFO]: [AsyncWorldEditInjector] * Error message: com.sk89q.worldedit.EditSession.ForceClassLoad()Ljava/lang/Class;
[14:18:48 INFO]: [AsyncWorldEditInjector] * Stack:
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:134)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.injector.InjectorManual.onEnable(InjectorManual.java:76)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.a.b(AsyncWorldEditLoader.java:389)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.primesoft.asyncworldedit.AsyncWorldEditMain.onEnable(AsyncWorldEditMain.java:269)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[14:18:48 INFO]: [AsyncWorldEditInjector] * org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[14:18:48 INFO]: [AsyncWorldEditInjector] * net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
[14:18:48 INFO]: [AsyncWorldEditInjector] * net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
[14:18:48 INFO]: [AsyncWorldEditInjector] * net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[14:18:48 INFO]: [AsyncWorldEditInjector] * net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
[14:18:48 INFO]: [AsyncWorldEditInjector] * net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[14:18:48 INFO]: [AsyncWorldEditInjector] * java.lang.Thread.run(Thread.java:745)
[14:18:48 INFO]: [AsyncWorldEditInjector] ****************************
[14:18:48 INFO]: [AsyncWorldEditInjector] Enabled
[14:18:48 INFO]: [AsyncWorldEdit] Plugin installed
[14:18:48 INFO]: [AsyncWorldEdit] BlocksHub plugin not found.
[14:18:49 INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix.
[14:18:49 INFO]: [AsyncWorldEdit] AsyncWorldEditInjector plugin not found, trying to initialize using static instances...
[14:18:49 INFO]: [AsyncWorldEditInjector] New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
[14:18:49 INFO]: [AsyncWorldEdit] Loading plugins...
[14:18:49 INFO]: [AsyncWorldEdit] Enabled
```

Any future attempt to use worldedit results in:

```
[14:21:53 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220) ~[worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.jar:?]
        at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:119) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:225) [worldedit-bukkit-6.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-f928e7a-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.IllegalAccessError: tried to access method com.sk89q.worldedit.EditSession.<init>(Lcom/sk89q/worldedit/util/eventbus/EventBus;Lcom/sk89q/worldedit/world/World;ILcom/sk89q/worldedit/extent/inventory/BlockBag;Lcom/sk89q/worldedit/event/extent/EditSessionEvent;)V from class com.sk89q.worldedit.AweEditSession
        at com.sk89q.worldedit.AweEditSession.<init>(AweEditSession.java:59) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.<init>(ThreadSafeEditSession.java:236) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.AsyncEditSession.<init>(AsyncEditSession.java:104) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:130) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:867) ~[?:?]
        at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:102) ~[?:?]
        ... 34 more
```

WorldEdit: Latest available from Bukkit Dev (http://dev.bukkit.org/bukkit-plugins/worldedit/files/61-world-edit-6-1-up-to-mc-1-8-8/)
AWE: 3.3.0, non-dev version

AWE 3.2.3 works, but has a different issue:

Using //flora results in:

```
[14:04:53 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.jar:?]
        at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:119) ~[AsyncWorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:225) [worldedit-bukkit-6.1.jar:?]
        at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-f928e7a-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.UnsupportedOperationException
        at io.netty.channel.nio.SelectedSelectionKeySet.iterator(SelectedSelectionKeySet.java:108) ~[server.jar:git-Spigot-f928e7a-e91aed8]
        at java.util.AbstractSet.hashCode(AbstractSet.java:122) ~[?:1.8.0_72-internal]
        at java.util.HashMap.hash(HashMap.java:338) ~[?:1.8.0_72-internal]
        at java.util.HashMap.containsKey(HashMap.java:595) ~[?:1.8.0_72-internal]
        at java.util.HashSet.contains(HashSet.java:203) ~[?:1.8.0_72-internal]
        at org.primesoft.asyncworldedit.injector.scanner.ClassScanner.scan(ClassScanner.java:167) ~[?:?]
        at org.primesoft.asyncworldedit.injector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:115) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:62) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.flora(RegionCommands.java:504) ~[?:?]
        ... 32 more
```

Same error occurs as well if you toggle your AWE off.

**Comment by SBPrime** [comment]
For dev version of WorldEdit you need AsyncWorldEdit-dev.jar
For WorldEdit versions from spigot you need AsyncWorldEdit.jar

After you install new version you need to remove the AsyncWorldEditInjector.jar

then do a reload.

Looks like you have a plugin that loads before AWE and that causes the injector to fail. TO fix the problem you need to do a full server restart (not reload!).

**Comment by U1F984** [comment]
I am not using /reload.

I know when to use the dev version and when not, the issue lies within your plugin (which is obvious, it is trying to call some method which does not exist)

**Comment by SBPrime** [comment]
Apparently it is not that obvious. The error is caused by the injector not kicking in. This can happen if you have a clean install (the injector is generated for the first time) and you have other plugins that use WorldEdit.

According to the log that you provided the injector was unable to inject some worldedit code. The error was caused by the WorldEdit classes being cached by the class loader. This can happen in 3 situations: 
1. You did a reload instead of a full restart
2. You use a plugin that loads before the injector and it uses WorldEdit
3. You used some sort of a plugin disable/enable plugin
   
   [14:18:48 INFO]: [AsyncWorldEditInjector] \* Exception: java.lang.NoSuchMethodError
   [14:18:48 INFO]: [AsyncWorldEditInjector] \* Error message: com.sk89q.worldedit.EditSession.ForceClassLoad()Ljava/lang/Class;

No such method is thrown because the class is already loaded and the injector class was not used.

Looks like you DID use reload, or you provided a log from the first plugin startup

```
[14:18:48 INFO]: [AsyncWorldEditInjector] Injector platform set to: Manual
```

To fix the issue you need to do a full server reload AFTER the injector is generated. The manual injection mode works in most cases but if you are using plugins that use WE and those plugins load before AWE its going to fail. If you do a restart the problem should fix itself.

Please do a server restart, and if the plugin still does not work for you please send me the startup log.

**Comment by U1F984** [comment]
I'm not able to create one now as I'm on mobile and can't access the
server, however I can assure you that I did do a full restart, saw the
error, tried using worldedit, stopped again after it failing and after
restarting saw the same error. I'll investigate further to find if any
other plugins are using worldedit. From your comments I assume your code
loads a modified worldedit edit session class, I will turn on JVM class
loading info so I can see when the class is loaded for the first time.
Thank you for your help so far!
Am 13.03.2016 13:31 schrieb "SBPrime" notifications@github.com:

**Comment by PikachuEXE** [comment]
I have similar problem too
Please se my startup log at http://pastebin.com/LTNtxtGz

If you want the log of first install please tell me

**Comment by SBPrime** [comment]
@PikachuEXE You need to use the asyncworldedit-dev.jar for dev versions of worldedit.

**Comment by PikachuEXE** [comment]
@SBPrime 
I understand
This is what I think:
[DEV version of AWE 3.3.1](https://www.spigotmc.org/resources/asyncworldedit-premium.9661/update?update=76034)
[Normal version of AWE 3.3.1](https://www.spigotmc.org/resources/asyncworldedit-premium.9661/update?update=76035)

I use the DEV version, but pressing "Download" will only give a file named "AsyncWorldEdit.jar"
If I have got a wrong version, where can I get the right version?

**Comment by SBPrime** [comment]
You need to go to version history. The "download" button always downloads the latest version.

**Comment by PikachuEXE** [comment]
OK thanks
I will reply with result with DEV version

**Comment by PikachuEXE** [comment]
It seems fine when testing with the DEV version from 
https://www.spigotmc.org/resources/asyncworldedit-premium.9661/history

tested with WE build b3458
Tried //copy & //paste

**Comment by SBPrime** [comment]
Plugin installation error.
