### ISSUE TITLE
Fix for Plotme 016 throwing null pointer exception

### ISSUE THREAD

**Issue by PikachuEXE** [SBPrime/AsyncWorldEdit-Premium#46]
# Env

AWE: `3.3.2 DEV` with `AsyncWorldEdit-PlotMeCore016 v3.3.0`
WE: `build 3458`
Plotme: 
- PlotMe-DefaultGenerator v0.16.1
- PlotMe v0.16.3
# Log

```
[16:08:46] [Server thread/INFO]: PikachuEXE issued server command: //stack
[16:08:46] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:220) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:119) ~[?:?]
    at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.1-SNAPSHOT-dist-b3458.jar:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-b704.jar:git-Spigot-cce4667-2bfda1f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.primesoft.asyncworldedit.plotme.PlotMeCoreFix_016.setMask(PlotMeCoreFix_016.java:101) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:134) ~[?:?]
    at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:866) ~[?:?]
    at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:102) ~[?:?]
    ... 34 more
```

**Comment by jaboy** [comment]
I know this is a month old, and i am sorry to be a party pooper, but plotme is no longer supported by its own developers
https://www.spigotmc.org/resources/plotme-official.2131/

You should change to plotsquared, it has many more functions, and it is really easy and simple to do :)

**Comment by PikachuEXE** [comment]
`PlotMe will return in Fall/Winter 2016`
Also I am talking about existing function broken, so if that plugin is not supported please remove it (the adapter and README)
But I think it will be a simple fix since the error is just `NullPointerException`

**Comment by SBPrime** [comment]
There was a bug in AWE plugin loading the plugins loaded to soon for PlotMe (plot me was not yet initialized).
