### ISSUE TITLE
Blocks Hub Error

### ISSUE THREAD

**Issue by Chalwk** [SBPrime/AsyncWorldEdit-Premium#48]
Running Spigot 1.9
- Blocks Hub appears to be functional, however, it is spamming the console with this error:
- Updated my server to 1.9 yesterday, that's when these errors started popping up.

`31.03 07:05:23 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
31.03 07:05:23 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
31.03 07:05:23 [Server] INFO at org.PrimeSoft.blocksHub.mcstats.MetricsLite$1.run(MetricsLite.java:156)
31.03 07:05:23 [Server] INFO at org.PrimeSoft.blocksHub.mcstats.MetricsLite.access$300(MetricsLite.java:49)
31.03 07:05:23 [Server] INFO at org.PrimeSoft.blocksHub.mcstats.MetricsLite.postPlugin(MetricsLite.java:267)
31.03 07:05:23 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
31.03 07:05:23 [Server] INFO at java.lang.Thread.run(Thread.java:745)
31.03 07:05:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
31.03 07:05:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
31.03 07:05:23 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
31.03 07:05:23 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BlocksHub v0.2 generated an exception while executing task 106
31.03 07:05:23 [Server] WARN Exception in thread "Craft Scheduler Thread - 10"`

**Comment by Chalwk** [comment]
Oh my goodness. I feel like an idiot. Please kindly disregard this issue. I was using an outdated version of BlocksHub, also, I just realized that I have posted this support ticket in the wrong place. My apologies.

Thanks!
