### ISSUE TITLE
Null ptr in player manager 

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit-Premium#76]
```
15.06 12:53:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'awe reload' in org.primesoft.asyncworldedit.platform.bukkit.AweCommand(awe)
15.06 12:53:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
15.06 12:53:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
15.06 12:53:18 [Server] INFO Caused by: java.lang.NullPointerException
15.06 12:53:18 [Server] INFO at org.primesoft.asyncworldedit.playerManager.PlayerManager.findPlayer(PlayerManager.java:286) ~[?:?]
15.06 12:53:18 [Server] INFO at org.primesoft.asyncworldedit.playerManager.PlayerManager.getPlayer(PlayerManager.java:238) ~[?:?]
15.06 12:53:18 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.BukkitPlatform.onCommand(BukkitPlatform.java:194) ~[?:?]
15.06 12:53:18 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.AweCommand.execute(AweCommand.java:63) ~[?:?]
15.06 12:53:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
15.06 12:53:18 [Server] INFO ... 14 more
```

**Comment by SBPrime** [comment]
From startup log:
`16.06 00:37:59 [Server] INFO [AsyncWorldEdit] Initializing WorldEdit. 
16.06 00:37:59 [Server] ERROR Could not pass event PluginEnableEvent to AsyncWorldEdit v3.3.10 
16.06 00:37:59 [Server] INFO org.bukkit.event.EventException 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] 
16.06 00:37:59 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.command.SimpleDescription.setDescription(Ljava/lang/String;)Lcom/sk89q/worldedit/util/command/SimpleDescription; 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.excommands.CommandsInjector.createGroup(CommandsInjector.java:170) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.excommands.CommandsInjector.injectCommands(CommandsInjector.java:99) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.worldedit.WorldEditIntegrator.initialize(WorldEditIntegrator.java:124) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.BukkitWorldeditIntegrator.initialize(BukkitWorldeditIntegrator.java:78) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.BukkitWorldeditIntegrator.<init>(BukkitWorldeditIntegrator.java:64) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.BukkitPlatform.initializeWorldEdit(BukkitPlatform.java:336) ~[?:?] 
16.06 00:37:59 [Server] INFO at org.primesoft.asyncworldedit.platform.bukkit.BukkitPlatform.onPluginEnabled(BukkitPlatform.java:315) ~[?:?] 
16.06 00:37:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92] 
16.06 00:37:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92] 
16.06 00:37:59 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92] 
16.06 00:37:59 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92] 
16.06 00:37:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397] 
16.06 00:37:59 [Server] INFO ... 13 more`

AWE version v3.3.10
WE version v6.1

Cause of the error: using mismatched versions of WE and AWE caused the plugin to crash on startup.
