### ISSUE TITLE
NPE after reload

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit-Premium#78]
```
[18:20:47 ERROR]: Error occurred while disabling AsyncWorldEdit v3.3.11 (Is it up to date?)
java.lang.NullPointerException
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onDisable(AsyncWorldEditBukkit.java:137) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:458) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:713) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:437) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c55900f-9af379f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]



...


...



[18:20:48 ERROR]: Error occurred while enabling AsyncWorldEdit v3.3.11 (Is it up to date?)
java.lang.NullPointerException
        at org.primesoft.asyncworldedit.playerManager.PlayerManager.addPlayer(PlayerManager.java:104) ~[?:?]
        at org.primesoft.asyncworldedit.platform.bukkit.BukkitPlayerProvider.initialize(BukkitPlayerProvider.java:111) ~[?:?]
        at org.primesoft.asyncworldedit.platform.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:170) ~[?:?]
        at org.primesoft.asyncworldedit.core.AsyncWorldEditCore.onEnable(AsyncWorldEditCore.java:261) ~[?:?]
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onEnable(AsyncWorldEditBukkit.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:745) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-c55900f-9af379f]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:437) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c55900f-9af379f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c55900f-9af379f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by Webbeh** [comment]
Also, after the reload, NPEs at every player login (http://paste.md-5.net/wavigetebo.avrasm) and upon every /awe command/subcommand (http://paste.md-5.net/pimolukori.profile)

**Comment by SBPrime** [comment]
Fixed
